[project]
name = "chorechart"
version = "0.1.0"
description = "User friendly UI for the Chore Chart administration"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "flask",
    "openpyxl>=3.1.5",
]
